sudo: required
language: node_js

node_js:
  - "0.10"

before_script:
  - npm install -g grunt-cli

deploy:
  provider: openshift
  user: "merloalejandro@gmail.com"
  password: "Mor15gan" # can be encrypted
  domain: "amerlo"
  app: nodejs